source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
target 'Attendance_iOS' do
    pod 'Firebase', '>= 2.5.1'
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
    pod 'CryptoSwift'
    pod 'Alamofire', '~> 3.4'
end